apiVersion: apps/v1
kind: Deployment
metadata:
  name: wow-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wow-db
  template:
    metadata:
      labels:
        app: wow-db
    spec:
      containers:
        - name: wow-db
          image: bitnamilegacy/mysql:8.4
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-password
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: ac-database-volume
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: [ "ALL" ]
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: ac-database-volume
          persistentVolumeClaim:
            claimName: ac-database-pvc
