apiVersion: v1
kind: Service
metadata:
  name: ac-worldserver
spec:
  selector:
    app: wow-world-server
  ports:
    - name: p-normal
      protocol: TCP
      port: 8085
      targetPort: 8085
    - name: p-soap
      protocol: TCP
      port: 7878
      targetPort: 7878
  type: NodePort
