apiVersion: apps/v1
kind: Deployment
metadata:
  name: wow-auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wow-auth-server
  template:
    metadata:
      labels:
        app: wow-auth-server
    spec:
      containers:
        - name: wow-auth-server
          image: acore/ac-wotlk-authserver:master
          ports:
            - containerPort: 3724
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-password
                  key: MYSQL_ROOT_PASSWORD
            - name: AC_LOGIN_DATABASE_INFO
              value: "ac-database;3306;root;$(MYSQL_ROOT_PASSWORD);acore_auth"
            - name: AC_LOGS_DIR
              value: "/azerothcore/env/dist/logs"
            - name: AC_TEMP_DIR
              value: "/azerothcore/env/dist/temp"
