apiVersion: v1
kind: Service
metadata:
  name: ac-authserver
spec:
  selector:
    app: wow-auth-server
  ports:
    - protocol: TCP
      port: 3724
      targetPort: 3724
      nodePort: 3724
  type: NodePort
